### ISSUE TITLE
Why is importing necessary?

### ISSUE THREAD

**Issue by axelson** [agleb/forensic#5]
Looking at the Readme I see "WARNING: Do not forget to import Forensic! require Forensic won't work!", but I don't understand why importing would be necessary if you are calling `Forensic.error` later (instead of simply `error`). Am I missing anything?

**Comment by agleb** [comment]
Sorry for replying that late!

You're right, this phrase is an artifact. Removed it.

**Comment by axelson** [comment]
Cool, thanks.
